// data.js - Batch 1 Update

const gameData = {
    crops: [
        // Previously added crops
        { id: 'carrot', name: 'Carrot', cost: 2, sell: 3, time: 2, icon: 'icons/imgi_2_carrot.webp' },
        { id: 'strawberry', name: 'Strawberry', cost: 3, sell: 5, time: 3, icon: 'icons/imgi_3_strawberry.webp' },
        { id: 'blueberry', name: 'Blueberry', cost: 4, sell: 6, time: 4, icon: 'icons/imgi_4_blueberry.webp' },
        { id: 'tomato', name: 'Tomato', cost: 5, sell: 8, time: 5, icon: 'icons/imgi_5_tomato.webp' },
        { id: 'cauliflower', name: 'Cauliflower', cost: 6, sell: 10, time: 6, icon: 'icons/imgi_6_cauliflower.webp' },
        { id: 'watermelon', name: 'Watermelon', cost: 20, sell: 29, time: 12, icon: 'icons/imgi_7_watermelon.webp' },
        { id: 'rafflesia', name: 'Rafflesia', cost: 100, sell: 165, time: 45, icon: 'icons/imgi_8_rafflesia.webp' },
        { id: 'green_apple', name: 'Green apple', cost: 9, sell: 14, time: 7, icon: 'icons/imgi_9_greenapple.webp' },
        { id: 'avocado', name: 'Avocado', cost: 10, sell: 15, time: 8, icon: 'icons/imgi_10_avocado.webp' },
        { id: 'banana', name: 'Banana', cost: 11, sell: 17, time: 9, icon: 'icons/imgi_11_banana.webp' },
        { id: 'pineapple', name: 'Pineapple', cost: 35, sell: 51, time: 25, icon: 'icons/imgi_12_pineapple.webp' },
        { id: 'kiwi', name: 'Kiwi', cost: 14, sell: 21, time: 10, icon: 'icons/imgi_13_kiwi.webp' },
        { id: 'bellpepper', name: 'Bell Pepper', cost: 15, sell: 23, time: 11, icon: 'icons/imgi_14_bellpepper.webp' },
        { id: 'pricklypear', name: 'Prickly Pear', cost: 16, sell: 25, time: 12, icon: 'icons/imgi_15_pricklypear.webp' },
        { id: 'loquat', name: 'Loquat', cost: 17, sell: 26, time: 13, icon: 'icons/imgi_16_loquat.webp' },
        { id: 'feijoa', name: 'Feijoa', cost: 18, sell: 28, time: 14, icon: 'icons/imgi_17_feijoa.webp' },
        { id: 'pitcherplant', name: 'Pitcher Plant', cost: 120, sell: 200, time: 50, icon: 'icons/imgi_18_pitcherplant.webp' },
        { id: 'orangetulip', name: 'Orange Tulip', cost: 125, sell: 210, time: 55, icon: 'icons/imgi_19_orangetulip.webp' },
        { id: 'corn', name: 'Corn', cost: 22, sell: 33, time: 15, icon: 'icons/imgi_20_corn.webp' },
        { id: 'daffodil', name: 'Daffodil', cost: 130, sell: 220, time: 60, icon: 'icons/imgi_21_daffodil.webp' },
        { id: 'pumpkin', name: 'Pumpkin', cost: 50, sell: 70, time: 30, icon: 'icons/imgi_22_pumpkin.webp' },
        { id: 'apple', name: 'Apple', cost: 25, sell: 38, time: 18, icon: 'icons/imgi_23_apple.webp' },
        { id: 'bamboo', name: 'Bamboo', cost: 26, sell: 40, time: 20, icon: 'icons/imgi_24_bamboo.webp' },
        { id: 'coconut', name: 'Coconut', cost: 28, sell: 43, time: 22, icon: 'icons/imgi_25_coconut.webp' },
        { id: 'cactus', name: 'Cactus', cost: 30, sell: 46, time: 24, icon: 'icons/imgi_26_cactus.webp' },
        { id: 'dragonfruit', name: 'Dragonfruit', cost: 250, sell: 400, time: 80, icon: 'icons/imgi_27_dragonfruit.webp' },
        { id: 'mango', name: 'Mango', cost: 40, sell: 60, time: 28, icon: 'icons/imgi_28_mango.webp' },
        { id: 'grape', name: 'Grape', cost: 32, sell: 48, time: 25, icon: 'icons/imgi_29_grape.webp' },
        { id: 'mushroom', name: 'Mushroom', cost: 35, sell: 55, time: 26, icon: 'icons/imgi_30_mushroom.webp' },
        { id: 'pepper', name: 'Pepper', cost: 38, sell: 58, time: 27, icon: 'icons/imgi_31_pepper.webp' },
        { id: 'cacao', name: 'Cacao', cost: 42, sell: 65, time: 29, icon: 'icons/imgi_32_cacao.webp' },
        { id: 'beanstalk', name: 'Beanstalk', cost: 300, sell: 475, time: 90, icon: 'icons/imgi_33_beanstalk.webp' },
        { id: 'emberlily', name: 'Emberlily', cost: 350, sell: 550, time: 100, icon: 'icons/imgi_34_emberlily.webp' },
        { id: 'sugarapple', name: 'Sugarapple', cost: 45, sell: 68, time: 30, icon: 'icons/imgi_35_sugarapple.webp' },
        { id: 'burningbud', name: 'Burning Bud', cost: 400, sell: 625, time: 110, icon: 'icons/imgi_36_burningbud.webp' },
        { id: 'giantpinecone', name: 'Giant Pinecone', cost: 5000, sell: 7777, time: 600, icon: 'icons/imgi_37_giantpinecone.webp' },
        { id: 'papaya', name: 'Papaya', cost: 48, sell: 72, time: 32, icon: 'icons/imgi_38_papaya.webp' },
        { id: 'passionfruit', name: 'Passionfruit', cost: 52, sell: 78, time: 34, icon: 'icons/imgi_39_passionfruit.webp' },
        { id: 'soulfruit', name: 'Soul Fruit', cost: 450, sell: 700, time: 120, icon: 'icons/imgi_40_soulfruit.webp' },
        { id: 'cursedfruit', name: 'Cursed Fruit', cost: 666, sell: 1332, time: 150, icon: 'icons/imgi_41_cursedfruit.webp' },
        { id: 'raspberry', name: 'Raspberry', cost: 55, sell: 83, time: 36, icon: 'icons/imgi_42_raspberry.webp' },
        { id: 'peach', name: 'Peach', cost: 58, sell: 88, time: 38, icon: 'icons/imgi_43_peach.webp' },
        { id: 'chocolatecarrot', name: 'Chocolate Carrot', cost: 60, sell: 92, time: 40, icon: 'icons/imgi_44_chocolatecarrot.webp' },
        
        // --- NEW CROPS BATCH 1 ---
        { id: 'redlolipop', name: 'Red Lolipop', cost: 1000, sell: 1700, time: 240, icon: 'icons/imgi_45_redlolipop.webp' },
        { id: 'candysunflower', name: 'Candy Sunflower', cost: 1100, sell: 1850, time: 250, icon: 'icons/imgi_46_candysunflower.webp' },
        { id: 'candyblossom', name: 'Candy Blossom', cost: 1200, sell: 2000, time: 260, icon: 'icons/imgi_47_candyblossom.webp' },
        { id: 'easteregg', name: 'Easter Egg', cost: 1000, sell: 1500, time: 200, icon: 'icons/imgi_48_easteregg.webp' },
        { id: 'cranberry', name: 'Cranberry', cost: 62, sell: 95, time: 42, icon: 'icons/imgi_49_cranberry.webp' },
        { id: 'durian', name: 'Durian', cost: 65, sell: 100, time: 45, icon: 'icons/imgi_50_durian.webp' },
        { id: 'eggplant', name: 'Eggplant', cost: 68, sell: 105, time: 48, icon: 'icons/imgi_51_eggplant.webp' },
        { id: 'lotus', name: 'Lotus', cost: 150, sell: 240, time: 70, icon: 'icons/imgi_52_lotus.webp' },
        { id: 'venusflytrap', name: 'Venus Flytrap', cost: 160, sell: 255, time: 75, icon: 'icons/imgi_53_venusflytrap.webp' },
        { id: 'nightshade', name: 'Nightshade', cost: 170, sell: 270, time: 80, icon: 'icons/imgi_54_nightshade.webp' },
        { id: 'mint', name: 'Mint', cost: 70, sell: 110, time: 50, icon: 'icons/imgi_55_mint.webp' },
        { id: 'glowshroom', name: 'Glowshroom', cost: 180, sell: 285, time: 85, icon: 'icons/imgi_56_glowshroom.webp' },
        { id: 'moonmelon', name: 'Moon Melon', cost: 190, sell: 300, time: 90, icon: 'icons/imgi_57_moonmelon.webp' },
        { id: 'starfruit', name: 'Starfruit', cost: 200, sell: 315, time: 95, icon: 'icons/imgi_58_starfruit.webp' },
        { id: 'moonflower', name: 'Moonflower', cost: 210, sell: 330, time: 100, icon: 'icons/imgi_59_moonflower.webp' },

        // --- NEW CROPS BATCH 2 ---
        { id: 'bloodbanana', name: 'Blood Banana', cost: 220, sell: 345, time: 105, icon: 'icons/imgi_60_bloodbanana.webp' },
        { id: 'moonglow', name: 'Moonglow', cost: 230, sell: 360, time: 110, icon: 'icons/imgi_61_moonglow.webp' },
        { id: 'moonblossom', name: 'Moonblossom', cost: 240, sell: 375, time: 115, icon: 'icons/imgi_62_moonblossom.webp' },
        { id: 'celestiberry', name: 'Celestiberry', cost: 250, sell: 390, time: 120, icon: 'icons/imgi_63_celestiberry.webp' },
        { id: 'moonmango', name: 'Moon Mango', cost: 260, sell: 405, time: 125, icon: 'icons/imgi_64_moonmango.webp' },
        { id: 'hive', name: 'Hive', cost: 2000, sell: 3200, time: 300, icon: 'icons/imgi_65_hive.webp' },
        { id: 'nectarine', name: 'Nectarine', cost: 72, sell: 115, time: 52, icon: 'icons/imgi_66_nectarine.webp' },
        { id: 'rose', name: 'Rose', cost: 75, sell: 120, time: 55, icon: 'icons/imgi_67_rose.webp' },
        { id: 'foxglove', name: 'Foxglove', cost: 78, sell: 125, time: 58, icon: 'icons/imgi_68_foxglove.webp' },
        { id: 'purpledahlia', name: 'Purple Dahlia', cost: 80, sell: 130, time: 60, icon: 'icons/imgi_69_purpledahlia.webp' },
        { id: 'pinklily', name: 'Pink Lily', cost: 82, sell: 135, time: 62, icon: 'icons/imgi_70_pinklily.webp' },
        { id: 'lilac', name: 'Lilac', cost: 85, sell: 140, time: 65, icon: 'icons/imgi_71_lilac.webp' },
        { id: 'sunflower', name: 'Sunflower', cost: 88, sell: 145, time: 68, icon: 'icons/imgi_72_sunflower.webp' },
        { id: 'lavender', name: 'Lavender', cost: 90, sell: 150, time: 70, icon: 'icons/imgi_73_lavender.webp' },
        { id: 'nectarshade', name: 'Nectarshade', cost: 2000, sell: 3500, time: 320, icon: 'icons/imgi_74_nectarshade.webp' },
        { id: 'manuka', name: 'Manuka', cost: 2200, sell: 3800, time: 340, icon: 'icons/imgi_75_manuka.webp' },
        { id: 'dandelion', name: 'Dandelion', cost: 92, sell: 155, time: 72, icon: 'icons/imgi_76_dandelion.webp' },
        { id: 'lumira', name: 'Lumira', cost: 2400, sell: 4100, time: 360, icon: 'icons/imgi_77_lumira.webp' },
        { id: 'honeysuckle', name: 'Honeysuckle', cost: 95, sell: 160, time: 75, icon: 'icons/imgi_78_honeysuckle.webp' },
        { id: 'beebalm', name: 'Beebalm', cost: 98, sell: 165, time: 78, icon: 'icons/imgi_79_beebalm.webp' },
        { id: 'nectarthorn', name: 'Nectarthorn', cost: 2600, sell: 4400, time: 380, icon: 'icons/imgi_80_nectarthorn.webp' },
        { id: 'suncoil', name: 'Suncoil', cost: 2800, sell: 4700, time: 400, icon: 'icons/imgi_81_suncoil.webp' },
        { id: 'crocus', name: 'Crocus', cost: 100, sell: 170, time: 80, icon: 'icons/imgi_82_crocus.webp' },
        { id: 'succulent', name: 'Succulent', cost: 105, sell: 175, time: 82, icon: 'icons/imgi_83_succulent.webp' },
        { id: 'violetcorn', name: 'Violetcorn', cost: 3000, sell: 5000, time: 420, icon: 'icons/imgi_84_violetcorn.webp' },
        { id: 'bendboo', name: 'Bendboo', cost: 3200, sell: 5300, time: 440, icon: 'icons/imgi_85_bendboo.webp' },
        { id: 'cocovine', name: 'Cocovine', cost: 3400, sell: 5600, time: 460, icon: 'icons/imgi_86_cocovine.webp' },
        { id: 'dragonpepper', name: 'Dragon Pepper', cost: 110, sell: 180, time: 85, icon: 'icons/imgi_87_dragonpepper.webp' },
        { id: 'wildcarrot', name: 'Wild Carrot', cost: 115, sell: 185, time: 88, icon: 'icons/imgi_88_wildcarrot.webp' },

        // --- FINAL BATCH ---
        { id: 'pear', name: 'Pear', cost: 120, sell: 190, time: 90, icon: 'icons/imgi_89_pear.webp' },
        { id: 'cantaloupe', name: 'Cantaloupe', cost: 125, sell: 195, time: 92, icon: 'icons/imgi_90_cantaloupe.webp' },
        { id: 'parasolflower', name: 'Parasol Flower', cost: 3600, sell: 5900, time: 480, icon: 'icons/imgi_91_parasolflower.webp' },
        { id: 'rosydelight', name: 'Rosy Delight', cost: 3800, sell: 6200, time: 500, icon: 'icons/imgi_92_rosydelight.webp' },
        { id: 'elephantears', name: 'Elephant Ears', cost: 130, sell: 200, time: 95, icon: 'icons/imgi_93_elephantears.webp' },
        { id: 'peacelily', name: 'Peace Lily', cost: 135, sell: 205, time: 98, icon: 'icons/imgi_94_peacelily.webp' },
        { id: 'delphinium', name: 'Delphinium', cost: 140, sell: 210, time: 100, icon: 'icons/imgi_95_delphinium.webp' },
        { id: 'travelersfruit', name: 'Travelers Fruit', cost: 4000, sell: 6500, time: 520, icon: 'icons/imgi_96_travelersfruit.webp' },
        { id: 'lilyofthevalley', name: 'Lily Of The Valley', cost: 145, sell: 215, time: 102, icon: 'icons/imgi_97_lilyofthevalley.webp' },
        { id: 'guanabana', name: 'Guanabana', cost: 155, sell: 225, time: 105, icon: 'icons/imgi_99_guanabana.webp' },
        { id: 'libertylily', name: 'Liberty Lily', cost: 4200, sell: 6800, time: 540, icon: 'icons/imgi_100_libertylily.webp' },
        { id: 'boneblossom', name: 'Boneblossom', cost: 4400, sell: 7100, time: 560, icon: 'icons/imgi_102_boneblossom.webp' },
        { id: 'stonebite', name: 'Stonebite', cost: 4600, sell: 7400, time: 580, icon: 'icons/imgi_103_stonebite.webp' },
        { id: 'paradisepetal', name: 'Paradise Petal', cost: 4800, sell: 7700, time: 600, icon: 'icons/imgi_104_paradisepetal.webp' },
        { id: 'horneddinoshroom', name: 'Horned Dinoshroom', cost: 5000, sell: 8000, time: 620, icon: 'icons/imgi_105_horneddinoshroom.webp' },
        { id: 'fireflyfern', name: 'Firefly Fern', cost: 5200, sell: 8300, time: 640, icon: 'icons/imgi_107_fireflyfern.webp' },
        { id: 'fossilight', name: 'Fossilight', cost: 5400, sell: 8600, time: 660, icon: 'icons/imgi_108_fossilight.webp' },
        { id: 'amberspine', name: 'Amberspine', cost: 5600, sell: 8900, time: 680, icon: 'icons/imgi_110_amberspine.webp' },
        { id: 'grandvolcania', name: 'Grand Volcania', cost: 5800, sell: 9200, time: 700, icon: 'icons/imgi_111_grandvolcania.webp' },
        { id: 'lingonberry', name: 'Lingonberry', cost: 160, sell: 230, time: 108, icon: 'icons/imgi_112_lingonberry.webp' },
        { id: 'monoblooma', name: 'Monoblooma', cost: 6000, sell: 9500, time: 720, icon: 'icons/imgi_113_monoblooma.webp' },
        { id: 'spikedmango', name: 'Spiked Mango', cost: 165, sell: 235, time: 110, icon: 'icons/imgi_114_spikedmango.webp' },
        { id: 'taroflower', name: 'Taro Flower', cost: 170, sell: 240, time: 112, icon: 'icons/imgi_115_taroflower.webp' },
        { id: 'softsunshine', name: 'Soft Sunshine', cost: 6200, sell: 9800, time: 740, icon: 'icons/imgi_116_softsunshine.webp' },
        { id: 'serenity', name: 'Serenity', cost: 6400, sell: 10100, time: 760, icon: 'icons/imgi_117_serenity.webp' },
        { id: 'zenflare', name: 'Zenflare', cost: 6600, sell: 10400, time: 780, icon: 'icons/imgi_118_zenflare.webp' },
        { id: 'zenrocks', name: 'Zenrocks', cost: 6800, sell: 10700, time: 800, icon: 'icons/imgi_119_zenrocks.webp' },
        { id: 'hinomai', name: 'Hinomai', cost: 7000, sell: 11000, time: 820, icon: 'icons/imgi_120_hinomai.webp' },
        
        // Older, higher-ID crops
        { id: 'aloevera', name: 'Aloe Vera', cost: 150, sell: 250, time: 60, icon: 'icons/imgi_98_aloevera.webp' },
        { id: 'fireworkflower', name: 'Firework Flower', cost: 750, sell: 1475, time: 180, icon: 'icons/imgi_101_fireworkflower.webp' },
        { id: 'boneboo', name: 'Boneboo', cost: 850, sell: 1650, time: 195, icon: 'icons/imgi_106_boneboo.webp' },
        { id: 'horsetail', name: 'Horsetail', cost: 1000, sell: 1950, time: 220, icon: 'icons/imgi_109_horsetail.webp' },
        { id: 'mapleapple', name: 'Maple Apple', cost: 800, sell: 1575, time: 195, icon: 'icons/imgi_121_mapleapple.webp' }
    ],
    pets: [
        { id: 'none', name: 'No Pet', multiplier: 1.0 },
        { id: 'chihuahua', name: 'Chihuahua (5%)', multiplier: 1.05 },
        { id: 'pug', name: 'Pug (10%)', multiplier: 1.10 },
        { id: 'cyborg_cat', name: 'Cyborg Cat (30%)', multiplier: 1.30 },
        { id: 'hydra', name: 'Hydra (50%)', multiplier: 1.50 }
    ],
    mutations: [
        // --- THE NEW, COMPREHENSIVE MUTATION LIST ---
        { id: 'none', name: 'No Mutation', multiplier: 1.0 },
        { id: 'gilded', name: 'Gilded (x1.5)', multiplier: 1.5 },
        { id: 'radioactive', name: 'Radioactive (x80)', multiplier: 80.0 },
        { id: 'shimmering', name: 'Shimmering (x3)', multiplier: 3.0 },
        { id: 'chromatic', name: 'Chromatic (x5)', multiplier: 5.0 },
        { id: 'gold', name: 'Gold (x20)', multiplier: 20.0 },
        { id: 'rainbow', name: 'Rainbow (x50)', multiplier: 50.0 },
        { id: 'shocked', name: 'Shocked (x100)', multiplier: 100.0 },
        { id: 'voidtouched', name: 'Voidtouched (x135)', multiplier: 135.0 },
        { id: 'wet', name: 'Wet (x1.2)', multiplier: 1.2 },
        { id: 'zombified', name: 'Zombified (x5)', multiplier: 5.0 },
        { id: 'celestial', name: 'Celestial (x120)', multiplier: 120.0 },
        { id: 'friendbound', name: 'Friendbound (x70)', multiplier: 70.0 },
        { id: 'toxic', name: 'Toxic (x1.2)', multiplier: 1.2 },
        { id: 'frozen', name: 'Frozen (x10)', multiplier: 10.0 },
        { id: 'chilled', name: 'Chilled (x2)', multiplier: 2.0 },
        { id: 'choc', name: 'Choc (x2)', multiplier: 2.0 },
        { id: 'moonlit', name: 'Moonlit (x2)', multiplier: 2.0 },
        { id: 'bloodlit', name: 'Bloodlit (x4)', multiplier: 4.0 },
        { id: 'disco', name: 'Disco (x25)', multiplier: 25.0 },
        { id: 'plasma', name: 'Plasma (x5)', multiplier: 5.0 },
        { id: 'pollinated', name: 'Pollinated (x3)', multiplier: 3.0 },
        { id: 'honeyglazed', name: 'Honeyglazed (x5)', multiplier: 5.0 },
        { id: 'dawnbound', name: 'Dawnbound (x150)', multiplier: 150.0 },
        { id: 'heavenly', name: 'Heavenly (x5)', multiplier: 5.0 },
        { id: 'cooked', name: 'Cooked (x10)', multiplier: 10.0 },
        { id: 'burnt', name: 'Burnt (x4)', multiplier: 4.0 },
        { id: 'molten', name: 'Molten (x25)', multiplier: 25.0 },
        { id: 'meteoric', name: 'Meteoric (x125)', multiplier: 125.0 },
        { id: 'windstruck', name: 'Windstruck (x2)', multiplier: 2.0 },
        { id: 'alienlike', name: 'Alienlike (x100)', multiplier: 100.0 },
        { id: 'sundried', name: 'Sundried (x85)', multiplier: 85.0 },
        { id: 'verdant', name: 'Verdant (x4)', multiplier: 4.0 },
        { id: 'paradisal', name: 'Paradisal (x100)', multiplier: 100.0 },
        { id: 'twisted', name: 'Twisted (x5)', multiplier: 5.0 },
        { id: 'galactic', name: 'Galactic (x120)', multiplier: 120.0 },
        { id: 'aurora', name: 'Aurora (x90)', multiplier: 90.0 },
        { id: 'cloudtouched', name: 'Cloudtouched (x5)', multiplier: 5.0 },
        { id: 'drenched', name: 'Drenched (x5)', multiplier: 5.0 },
        { id: 'fried', name: 'Fried (x8)', multiplier: 8.0 },
        { id: 'amber', name: 'Amber (x10)', multiplier: 10.0 },
        { id: 'oldamber', name: 'Oldamber (x20)', multiplier: 20.0 },
        { id: 'ancientamber', name: 'Ancientamber (x50)', multiplier: 50.0 },
        { id: 'sandy', name: 'Sandy (x3)', multiplier: 3.0 },
        { id: 'clay', name: 'Clay (x5)', multiplier: 5.0 },
        { id: 'ceramic', name: 'Ceramic (x30)', multiplier: 30.0 },
        { id: 'tempestous', name: 'Tempestous (x12)', multiplier: 12.0 },
        { id: 'infected', name: 'Infected (x75)', multiplier: 75.0 },
        { id: 'tranquil', name: 'Tranquil (x20)', multiplier: 20.0 },
        { id: 'chakra', name: 'Chakra (x15)', multiplier: 15.0 },
        { id: 'foxfire', name: 'Foxfire (x90)', multiplier: 90.0 }
    ]
};